import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import Heading from '../components/shared/Heading';
import Body from '../components/shared/Body';
import Footer from '../components/Footer/Footer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Heading size={5} gutter='xs' color='#fff'>
          The World Awaits
        </Heading>
        <Body gutter='xs' color='#fff'>
          Words from the President, Vanessa Genger: My fascination with travel began while growing
          up in Venezuela and Thailand. I traveled throughout Europe and the Far East with my family
          and as a member of the Bangkok Aquatic swim team. I fell in love with exploring the world
          and getting to know cities such as Athens, Rome, and Vienna. After a career in customer
          relations and logistics, I launched my career as a travel advisor, and have found true
          passion in helping my clients immerse themselves in local culture. My trips are
          personalized for each individual client. My areas of specialty include France, Italy,
          Spain, Ireland and New Zealand, and I travel often to Prague, where my daughter is a
          teacher. I’ve cruised Sydney Harbour in Australia, explored both islands of New Zealand,
          toured Italy with my three daughters during the Christmas holidays, attended Easter Mass
          in the Cordoba Mosque-Cathedral in Spain, and driven the northern coast of Ireland from
          Galway to Dublin. I’ve been lucky to experience several trips of a lifetime, and my goal
          is to create similar experiences for my clients!
        </Body>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
